"""empty message

Revision ID: dc43f3bacfd7
Revises: 5ba9c4bf8ada
Create Date: 2024-02-02 21:09:39.330392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc43f3bacfd7'
down_revision = '5ba9c4bf8ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('plants', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('plants', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'price')
    op.drop_column('plants', 'image')
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
